import React, { createContext, useContext, useState } from 'react';

type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, replacements?: Record<string, string | number>, fallback?: string) => string;
}

const translations = {
  tr: {
    // Navigation / Tabs
    "nav.home": "Ana Sayfa",
    "nav.reports": "Raporlar",
    "nav.chequesNotes": "Çek & Senet",
    "nav.settings": "Ayarlar",
    "nav.title": "Gelir Gider Takip",
    "nav.transactions": "İşlemler",
    "nav.goals": "Hedefler",
    "nav.viewAllProjects": "Tüm Şirketleri Görüntüle",
    "nav.allProjects": "Tüm Şirketler",
    "nav.subTitle": "Kişisel finans yöneticiniz",
    "summary.totalBalance": "Toplam Bakiye",

    // General Words
    "general.income": "Gelir",
    "general.expense": "Gider",
    "general.amount": "Tutar",
    "general.description": "Açıklama",
    "general.category": "Kategori",
    "general.date": "Tarih",
    "general.paymentMethod": "Ödeme Yöntemi",
    "general.project": "Şirket / Proje",
    "general.none": "Belirtilmemiş",
    "general.cash": "Nakit",
    "general.creditCard": "Kredi Kartı",
    "general.actions": "İşlemler",
    "general.save": "Kaydet",
    "general.cancel": "İptal",
    "general.delete": "Sil",
    "general.edit": "Düzenle",
    "general.active": "Aktif",
    "general.passive": "Pasif",
    "general.loading": "Yükleniyor...",
    "general.search": "İşlemlerde ara...",
    "general.all": "Tümü",
    "general.personal": "Kişisel (Şirket Dışı)",
    "general.required": "Bu alan zorunludur",
    "general.success": "Başarılı",
    "general.error": "Hata",
    "general.type": "Tür",
    "general.unknown": "Bilinmeyen",
    "general.currency": "Döviz",
    "general.cashEmoji": "💵 Nakit",
    "general.cardEmoji": "💳 Kredi Kartı",
    "form.addIncome": "Gelir Ekle",
    "form.addExpense": "Gider Ekle",
    "form.selectDate": "Tarih seçin",
    "form.descriptionOptional": "Açıklama (Opsiyonel)",

    // Summary Cards
    "summary.totalIncome": "Toplam Gelir",
    "summary.totalExpense": "Toplam Gider",
    "summary.netBalance": "Net Bakiye",
    "summary.transactionCount": "İşlem Sayısı",

    // Forms
    "form.addNewTransaction": "Yeni İşlem Ekle",
    "form.editTransaction": "İşlemi Düzenle",
    "form.editTransactionDesc": "Seçili işlemin detaylarını güncelleyin.",
    "form.mathHint": "0.00 veya 100+50-20...",
    "form.selectCategory": "Kategori seçin",
    "form.selectPaymentMethod": "Ödeme yöntemi seçin",
    "form.selectProject": "Şirket/Proje seçin",
    "form.optional": "Opsiyonel",
    "form.notePlaceholder": "İşlem hakkında not...",
    "form.submitAdd": "Ekle",
    "form.quickTemplates": "Hızlı Şablonlar",
    
    // Recurring Forms
    "form.addNewRecurring": "Sabit İşlem Ekle",
    "form.startDate": "Başlangıç Tarihi",
    "form.endDate": "Bitiş Tarihi",
    "form.hasEndDate": "Bitiş tarihi var",
    "form.isActive": "Aktif",
    "form.selectStartDate": "Başlangıç tarihi seçin",
    "form.selectEndDate": "Bitiş tarihi seçin",
    "form.addRecurringIncome": "Sabit Gelir Ekle",
    "form.addRecurringExpense": "Sabit Gider Ekle",

    // Recurring Manager
    "rec.title": "Sabit İşlemler",
    "rec.desc": "Maaş, kira, abonelik gibi her ay düzenli tekrarlanan işlemlerinizi buradan yönetin. Sistem bu işlemleri vadesi geldikçe otomatik olarak ekler.",
    "rec.addNew": "Yeni Sabit İşlem",
    "rec.activeState": "Durum",
    "rec.noItems": "Henüz tanımlanmış sabit işlem bulunmuyor.",
    "rec.addFirst": "Yukarıdaki formu kullanarak ilk sabit işleminizi oluşturun!",

    // Filter Bar
    "filter.viewMode": "Görünüm Modu",
    "filter.daily": "Günlük",
    "filter.monthly": "Aylık",
    "filter.yearly": "Yıllık",
    "filter.customRange": "Özel Tarih Aralığı",
    "filter.minAmount": "Min Tutar",
    "filter.maxAmount": "Max Tutar",
    "filter.categories": "Kategoriler",
    "filter.reset": "Filtreleri Temizle",
    "filter.advanced": "Gelişmiş Filtreler",
    "month.jan": "Ocak", "month.feb": "Şubat", "month.mar": "Mart", "month.apr": "Nisan", "month.may": "Mayıs", "month.jun": "Haziran",
    "month.jul": "Temmuz", "month.aug": "Ağustos", "month.sep": "Eylül", "month.oct": "Ekim", "month.nov": "Kasım", "month.dec": "Aralık",
    "filter.view": "Görünüm:",
    "form.startDateShort": "Başlangıç",
    "form.endDateShort": "Bitiş",
    "filter.txDesc": "İşlem Açıklaması",
    "filter.searchPlaceholder": "Açıklamalarda ara...",
    "filter.allMethods": "Tüm Yöntemler",
    "filter.cashOnly": "💵 Sadece Nakit",
    "filter.cardOnly": "💳 Sadece Kredi Kartı",
    "filter.amountRange": "Tutar Aralığı",
    "filter.clearSelection": "Seçimi Temizle",
    "filter.resetAll": "Tüm Filtreleri Sıfırla",

    // Charts
    "chart.monthlyTrend": "Gelir vs Gider Dağılımı",
    "chart.cashFlow": "6 Aylık Nakit Akışı ve Bakiye Tahmini (Sabit İşlemler Dahil)",
    "chart.incomeDistribution": "Gelir Dağılımı",
    "chart.expenseDistribution": "Gider Dağılımı",
    "chart.companySummary": "Şirket Dağılımı Özet Raporu",
    "chart.noData": "Veri bulunmuyor",

    // Cheques and Notes
    "cn.title": "Çek ve Senet Yönetimi",
    "cn.desc": "Alacak ve borç çek/senetlerinizi kaydedin, vadelerini takip edin ve günü geldiğinde tek tıklamayla işlemlere aktarın.",
    "cn.addNew": "Yeni Çek/Senet Ekle",
    "cn.cheque": "Çek",
    "cn.promissoryNote": "Senet",
    "cn.receivable": "Alacak",
    "cn.payable": "Borç",
    "cn.debtor": "Borçlu / Ödeyecek Kişi",
    "cn.bank": "Banka / Şube",
    "cn.serial": "Seri Numarası",
    "cn.dueDate": "Vade Tarihi",
    "cn.issueDate": "Düzenleme Tarihi",
    "cn.status": "Durum",
    "cn.pending": "Beklemede",
    "cn.paid": "Tahsil Edildi / Ödendi",
    "cn.cancelled": "İptal Edildi",
    "cn.returned": "İade Edildi",
    "cn.noItems": "Henüz kayıtlı çek veya senet bulunmuyor.",
    "cn.createTransaction": "İşlemlere Aktar",
    "cn.transferred": "İşlemlere başarıyla aktarıldı.",
    "cn.reminderTitle": "Çek & Senet Hatırlatıcı",
    "cn.reminderDesc": "Vadeli alacak ve borç belgelerinizi yönetin.",
    "cn.totalReceivables": "Toplam Alacak",
    "cn.pendingCollections": "Beklemedeki tahsilatlar",
    "cn.totalPayables": "Toplam Borç",
    "cn.pendingPayments": "Beklemedeki ödemeler",
    "cn.dueOverdue": "Vadesi Gelenler / Geçenler",
    "cn.itemsCount": "{count} Adet",
    "cn.totalPrefix": "Toplam: ",
    "cn.searchPlaceholder": "Borçlu adı, seri no veya açıklama ara...",
    "cn.allDocs": "Tüm Belgeler",
    "cn.allDirections": "Tüm Yönler",
    "cn.allStatuses": "Tüm Durumlar",
    "cn.collectedPaidStatus": "Tahsil Edildi/Ödendi",
    "cn.bouncedReturnedStatus": "Karşılıksız/İade",
    "cn.docDetail": "Belge Detayı",
    "cn.serialBank": "Seri No / Banka",
    "cn.dueIssue": "Vade / Keşide",
    "cn.bankNotSpecified": "Banka belirtilmemiş",
    "cn.overdueLabel": "Gecikti",
    "cn.todayLabel": "Bugün!",
    "cn.duePrefix": "Vade: ",
    "cn.issuePrefix": "Keşide: ",
    "cn.markPaidTooltip": "Tahsil Edildi / Ödendi İşaretle",
    "cn.debtorCreditor": "Borçlu/Alacaklı",
    "cn.addNewDoc": "Yeni Çek / Senet Ekle",
    "cn.addNewDocTitle": "Yeni Çek veya Senet Ekle",
    "cn.addNewDocDesc": "Vadeli alacak veya borç belgesi detaylarını girin.",
    "cn.docType": "Belge Türü",
    "cn.selectPlaceholder": "Seçin",
    "cn.docDirection": "Yön / İşlem",
    "cn.receivableReceived": "Alacak (Alınan)",
    "cn.payableIssued": "Borç (Verilen)",
    "cn.amountTL": "Tutar (TL)",
    "cn.serialPlaceholder": "Çek/Senet Seri No...",
    "cn.issueDateLabel": "Keşide / Düzenleme Tarihi",
    "cn.debtorPlaceholder": "Ad Soyad / Firma...",
    "cn.bankPlaceholder": "Garanti, Akbank vb...",
    "cn.relatedProject": "İlişkili Şirket / Proje",
    "cn.selectCompanyOptional": "Şirket Seçin (Opsiyonel)",
    "cn.noAssociation": "İlişkilendirme Yok",
    "cn.notesPlaceholder": "Ek notlar girin...",
    "cn.editDocTitle": "Belgeyi Düzenle",
    "cn.editDocDesc": "Mevcut çek veya senet kaydını düzenleyin.",
    "cn.docStatus": "Belge Durumu",
    "cn.selectStatus": "Durum Seçin",
    "cn.cancelledStatusFull": "İptal Edildi",
    "cn.returnedStatusFull": "Karşılıksız/İade",
    "cn.updateStatusTitle": "{type} Durumunu Güncelle",
    "cn.updateStatusDesc": "Bu belgeyi **Tahsil Edildi / Ödendi** olarak işaretlemek üzeresiniz.",
    "cn.docDetailsTitle": "Belge Detayları",
    "cn.autoRecordLedger": "Kasaya (İşlemlere) otomatik gelir/gider olarak kaydet",
    "cn.ledgerCategory": "İşlemin Ekleneceği Kategori",
    "cn.dismissBtn": "Vazgeç",
    "cn.confirmPaymentBtn": "Tahsil Et / Ödendi İşaretle",
    "cn.deleteTitle": "Kayıt Silinecek",
    "cn.deleteDesc": "Bu çek/senet kaydını silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
    "cn.deleteConfirmBtn": "Evet, Sil",

    // Settings
    "settings.title": "Uygulama Seçenekleri",
    "settings.theme": "Arayüz Teması",
    "settings.themeLight": "Açık Tema (Light Mode)",
    "settings.themeDark": "Koyu Tema (Dark Mode)",
    "settings.themeSystem": "Sistem Teması (System Default)",
    "settings.currency": "Varsayılan Para Birimi",
    "currency.try": "Türk Lirası (₺ - TRY)",
    "currency.usd": "Amerikan Doları ($ - USD)",
    "currency.eur": "Euro (€ - EUR)",
    "currency.gbp": "İngiliz Sterlini (£ - GBP)",
    "settings.autoLock": "Otomatik Kilit Süresi",
    "settings.autoLockDisabled": "Devre Dışı (Kilitlenmesin)",
    "settings.autoLockMin": "{min} Dakika Hareketsizlik",
    "settings.autoLockDesc": "Uygulamada herhangi bir hareket olmazsa ekran otomatik olarak kilitlenir. (Sadece şifre koruması aktifken çalışır)",
    "settings.language": "Dil / Language",
    
    // Backup and Cloud
    "settings.backupTitle": "Yerel Veri Yedekleme & Geri Yükleme",
    "settings.backupDesc": "Yerel verilerinizi JSON dosyası olarak bilgisayarınıza yedekleyebilir veya daha önce aldığınız bir yedek dosyasından verilerinizi geri yükleyebilirsiniz.",
    "settings.backupExport": "Yedek İndir (JSON)",
    "settings.backupImport": "Yedek Yükle (JSON)",
    "settings.cloudTitle": "Bulut Senkronizasyonu",
    "settings.cloudDesc": "Hesabınızla giriş yaparak verilerinizi güvenle bulutta saklayabilir ve diğer cihazlarınızla senkronize edebilirsiniz.",
    "settings.cloudDelete": "Bulut Verilerini Sil",
    "settings.cloudDeleteConfirm": "Tüm bulut verilerinizi silmek için 'ONAYLIYORUM' yazın:",
    
    // Encryption / Password Settings
    "settings.passTitle": "Ekran Kilidi & Şifreleme",
    "settings.passDesc": "Uygulamanın açılışında şifre koruması ekleyerek yerel verilerinizin şifrelenmesini sağlayın.",
    "settings.passEnable": "Şifre Korumasını Aktif Et",
    "settings.passDisable": "Şifre Korumasını Kaldır",

    "general.downloadCSV": "CSV İndir",
    "list.noItems": "Aradığınız kriterlere uygun işlem bulunamadı.",
    "form.paymentMethodOptional": "Ödeme Yöntemi (Opsiyonel)",
    "list.deleteTransaction": "İşlemi Sil",
    "list.deleteConfirm": "Bu işlemi silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",

    // Toasts and Dialogs
    "toast.saved": "Başarıyla kaydedildi.",
    "toast.updated": "Başarıyla güncellendi.",
    "toast.deleted": "Başarıyla silindi.",
    "toast.error": "Bir hata oluştu.",
    "toast.backupSuccess": "Yedek başarıyla yüklendi.",
    "toast.currencySet": "Varsayılan para birimi {val} olarak ayarlandı.",
    "toast.languageSet": "Uygulama dili Türkçe olarak ayarlandı.",
    "toast.syncSuccess": "Bulut senkronizasyonu tamamlandı.",
    "toast.connectionRestored": "İnternet bağlantısı sağlandı, bekleyen değişiklikler yükleniyor...",
    "toast.newerDataFound": "Bulutta daha yeni veri tespit edildi, verileriniz senkronize edildi.",
    "toast.deleteCancelled": "Veri silme işlemi onaylanmadığı için iptal edildi.",
    "toast.dataCleared": "Bulut ve yerel verileriniz başarıyla temizlendi.",
    "toast.cloudSynced": "Buluttaki güncel verileriniz eşitlendi.",
    "toast.localNewer": "Yerel verileriniz buluttan daha yeni, değişiklikler yükleniyor...",
    "toast.realtimeSynced": "Diğer cihazdan gelen yeni veriler eşitlendi.",
    "cloud.deleteSuccess": "Buluttaki ve bu cihazdaki verileriniz kalıcı olarak silindi. Hesabınızdan çıkış yapıldı.",
    "cloud.deleteFailed": "Hesap verileri silinemedi.",
    "proj.selectLaunchTitle": "İşlem Yapılacak Şirketi Seçin",
    "proj.selectLaunchDesc": "Giriş yapmak ve gelir-gider işlemlerinizi yönetmek istediğiniz şirketi seçin:",
    "general.addTransaction": "İşlem Ekle",
    "general.single": "Tek Seferlik",
    "general.recurring": "Tekrarlı İşlem",
    "toast.fillFields": "Lütfen tüm zorunlu alanları geçerli değerlerle doldurun.",
    "toast.invalidContribution": "Lütfen geçerli bir katkı tutarı girin.",
    "toast.contributionSuccess": "Hedef birikimine başarıyla katkıda bulunuldu.",
    "login.verifying": "Giriş doğrulanıyor...",
    "changelog.title": "Yeni Güncelleme: v1.1.4",
    "changelog.subtitle": "Gelir Gider Takip yenilendi!",
    "changelog.desc": "Uygulamamıza çoklu para birimi ve gelişmiş Excel/CSV raporlama özelliklerini getirdik. İşte v1.1.4 sürümüyle gelen yenilikler:",
    "changelog.multiCurrency": "Çoklu Para Birimi Desteği",
    "changelog.multiCurrencyDesc": "İşlem bazlı döviz seçimi (TRY, USD, EUR) eklendi. Tüm finansal özetleriniz, grafikleriniz ve öngörüleriniz otomatik olarak seçtiğiniz varsayılan para biriminde hesaplanır.",
    "changelog.liveRates": "Canlı Döviz Kurları",
    "changelog.liveRatesDesc": "Uygulama açılışında en güncel kurlar internet üzerinden otomatik çekilir, böylece anlık ve doğru bakiye çevrimleri yapılır. Çevrimdışı çalışırken ise güvenli varsayılan kurlar kullanılır.",
    "changelog.export": "Excel (CSV) Dışa Aktarım",
    "changelog.exportDesc": "Raporlar sekmesinden tüm işlem dökümlerinizi Türkçe karakter ve UTF-8 BOM uyumlu olarak Excel'e (CSV) tek tıkla aktarabilirsiniz.",
    "changelog.fixes": "Hata Düzeltmeleri & Grafik Düzeltimi",
    "changelog.fixesDesc": "Kasa akışı simülasyon grafiğindeki görsel kesik çizgi hatası giderildi, şablon hedeflerinin filtre senkronizasyonu mükemmelleştirildi.",

    // Category Manager
    "cat.title": "Kategoriler",
    "cat.new": "Yeni",
    "cat.incomeTitle": "Gelir Kategorileri",
    "cat.expenseTitle": "Gider Kategorileri",
    "cat.editTitle": "Kategoriyi Düzenle",
    "cat.addTitle": "Yeni Kategori Ekle",
    "cat.editDesc": "Kategori detaylarını güncelleyin.",
    "cat.addDesc": "Yeni bir gelir veya gider kategorisi oluşturun.",
    "cat.nameLabel": "Kategori Adı",
    "cat.namePlaceholder": "Örn: Market, Ulaşım...",
    "cat.typeLabel": "Tür",
    "cat.budgetLimit": "Aylık Bütçe Limiti ({symbol}) (Opsiyonel)",
    "cat.budgetPlaceholder": "Örn: 5000",
    "cat.budgetDesc": "Bu harcama kategorisi için aylık maksimum limit belirler.",
    "cat.colorLabel": "Renk",
    "cat.updateBtn": "Güncelle",
    "cat.addBtn": "Ekle",
    "cat.deleteTitle": "Kategoriyi Sil",
    "cat.deleteDesc": "Bu kategoriyi silmek istediğinizden emin misiniz? Bu kategoriye ait işlemler otomatik olarak **\"Diğer\"** kategorisine atanacaktır.",
    "cat.other": "Diğer",
    "cat.limitShort": "L",

    // Project Manager
    "proj.title": "Şirketler / Projeler",
    "proj.new": "Yeni",
    "proj.all": "Tüm Şirketler",
    "proj.empty": "Henüz şirket/proje eklenmemiş",
    "proj.passive": "Pasif",
    "proj.editTitle": "Şirket/Projeyi Düzenle",
    "proj.addTitle": "Yeni Şirket/Proje Ekle",
    "proj.editDesc": "Şirket veya proje detaylarını güncelleyin.",
    "proj.addDesc": "Yeni bir şirket veya proje oluşturun.",
    "proj.nameLabel": "Ad",
    "proj.namePlaceholder": "Örn: Ana Şirket, Proje A...",
    "proj.descLabel": "Açıklama (Opsiyonel)",
    "proj.descPlaceholder": "Şirket/proje hakkında kısa bilgi...",
    "proj.colorLabel": "Renk",
    "proj.activeLabel": "Aktif",
    "proj.deleteTitle": "Şirket/Projeyi Sil",
    "proj.deleteDesc": "Bu şirket/projeyi silmek istediğinizden emin misiniz? Bu projeye ait işlemler projeden çıkarılacaktır.",

    // Password Protection
    "pass.lockedTitle": "Uygulama Kilitli",
    "pass.enterPass": "Uygulamaya erişmek için şifrenizi girin",
    "pass.placeholder": "Şifreniz",
    "pass.errorInvalid": "Hatalı şifre veya veriler çözülemedi",
    "pass.errorGeneral": "Bir hata oluştu",
    "pass.unlocking": "Çözülüyor...",
    "pass.unlockBtn": "Kilidi Aç",
    "pass.forgotBtn": "Şifremi Unuttum",
    "pass.resetTitle": "Şifreyi Sıfırla",
    "pass.resetDesc": "Şifrenizi sıfırlamak için Google hesabınızla yeniden giriş yapmanız gerekmektedir. <br /><br /><strong class=\"text-amber-600 dark:text-amber-400\">Önemli Uyarı:</strong> Parolanız unutulduğu için şifrelenmiş yerel verileriniz çözülemeyecek ve bu cihazdan temizlenecektir. Google ile giriş yaptıktan sonra, buluttaki verileriniz (Supabase) otomatik olarak geri yüklenecektir.<br /><br />Bu işlem için mevcut oturumunuz kapatılacak ve Google giriş ekranına yönlendirileceksiniz. İnternet bağlantınızın olduğundan emin olun.",
    "pass.resetConfirmBtn": "Evet, Çıkış Yap ve Sıfırla",
    "pass.settingsTitle": "Şifre Koruması",
    "pass.statusActive": "Şifre koruması aktif (Veriler diskte şifreli saklanıyor)",
    "pass.removeBtn": "Şifre Korumasını Kaldır",
    "pass.newLabel": "Yeni Şifre",
    "pass.newPlaceholder": "En az 4 karakter",
    "pass.confirmLabel": "Şifreyi Onayla",
    "pass.confirmPlaceholder": "Şifreyi tekrar girin",
    "pass.settingUp": "Ayarlanıyor...",
    "pass.setupBtn": "Şifre Ayarla",
    "pass.errorShort": "Şifre en az 4 karakter olmalı",
    "pass.errorMismatch": "Şifreler eşleşmiyor",
    "pass.successSet": "Şifre başarıyla ayarlandı. Verileriniz yerel olarak şifrelendi.",
    "pass.errorSet": "Şifre ayarlanırken bir hata oluştu.",
    "pass.successRemove": "Şifre kaldırıldı. Verileriniz artık şifresiz saklanıyor.",
    "pass.errorRemove": "Şifre kaldırılırken bir hata oluştu.",
    "pass.hint": "Şifre koruması aktif olduğunda, uygulamaya her girişte şifre istenecek ve tüm yerel veriler şifrelenmiş olarak saklanacaktır.",

    // Cloud Sync
    "cloud.title": "Bulut Senkronizasyonu",
    "cloud.notConfigured": "Supabase yapılandırılmamış (.env dosyasını kontrol edin).",
    "cloud.loading": "Bulut işlemi yapılıyor...",
    "cloud.success": "Bulut işlemi başarılı.",
    "cloud.error": "Bulut işlemi başarısız.",
    "cloud.offline": "Çevrimdışı moddasınız.",
    "cloud.connected": "Buluta bağlısınız.",
    "cloud.envMissing": "Supabase ayarları yapılmamış. Lütfen .env dosyanıza VITE_SUPABASE_URL ve VITE_SUPABASE_ANON_KEY ekleyin.",
    "cloud.googleUser": "Google kullanıcısı",
    "cloud.offlineError": "Çevrimdışı durumdasınız. Bağlantı geldiğinde otomatik eşitlenecek.",
    "cloud.downloadError": "Veriler indirilemedi.",
    "cloud.signOut": "Çıkış",
    "cloud.deleteTitle": "Bulut Verilerini Sil",
    "cloud.deleteDesc": "Bu işlem buluttaki verilerinizi siler ve çıkış yapar.",
    "cloud.deletePrompt": "Hesap verilerinizi buluttan ve yerel depolamadan kalıcı olarak silmek istediğinizden emin misiniz?\n\nBu işlem geri alınamaz. Onaylamak için kutuya büyük harflerle 'ONAYLIYORUM' yazın:",
    "cloud.deleteBtn": "Bulut Verilerini Sil",
    "cloud.online": "Çevrimiçi",
    "cloud.offlineBadge": "Çevrimdışı",
    "cloud.syncPending": "Eşitleme Bekliyor",
    "cloud.uploadBtn": "Buluta Yükle",
    "cloud.downloadBtn": "Buluttan İndir",
    "cloud.hint": "Verileriniz Supabase üzerinde kullanıcı hesabınıza bağlı olarak saklanır. İsterseniz cihazınızda yerel olarak tutulmaya devam eder; buluta yükleme ve indirme işlemleri tamamen sizin kontrolünüzdeki yerlerdedir.",

    // Google Login
    "login.title": "Gelir Gider Takip",
    "login.subtitle": "Devam etmek için Google hesabınızla giriş yapın",
    "login.btn": "Google ile Giriş Yap",
    "login.hint": "Giriş yaptığınızda verileriniz güvenli şekilde bulutta senkronize edilir.",
    "login.envMissing": "Supabase yapılandırılmamış. .env dosyanıza VITE_SUPABASE_URL ve VITE_SUPABASE_ANON_KEY ekleyin.",

    // General Additional
    "general.add": "Ekle",
    "general.showHide": "Göster/Gizle",
    "general.total": "Toplam",
    "general.prediction": "Öngörü",

    // Transactions Additional
    "transactions.selectedPeriodTransactions": "Seçili Dönem İşlemleri",
    "transactions.dailyTransactions": "Günlük İşlemler",
    "transactions.monthlyTransactions": "Aylık İşlemler",
    "transactions.yearlyTransactions": "Yıllık İşlemler",

    // Goals Additional
    "goals.newGoal": "Yeni Hedef Belirle",
    "goals.nameLabel": "Hedef Adı *",
    "goals.namePlaceholder": "Örn: Yeni Bilgisayar, Tatil...",
    "goals.targetLabel": "Hedef Tutar ({symbol}) *",
    "goals.targetPlaceholder": "Örn: 50000",
    "goals.dateLabel": "Hedef Tarihi *",
    "goals.projectAssociation": "Şirket / Proje İlişkisi",
    "goals.personalOption": "🏢 Kişisel (Şirket Dışı)",
    "goals.saveGoal": "Hedefi Kaydet",
    "goals.activeGoals": "🎯 Aktif Finansal Hedefleriniz",
    "goals.totalGoals": "Toplam: {count} Hedef",
    "goals.completedBadge": "Tamamlandı 🎉",
    "goals.deleteGoal": "Hedefi Sil",
    "goals.progressLabel": "İlerleme: %{progress}",
    "goals.dueDate": "Vade Tarihi:",
    "goals.daysLeft": "{count} gün kaldı",
    "goals.overdue": "Vadesi geçmiş",
    "goals.remainingAmount": "Kalan Tutar:",
    "goals.contributionPlaceholder": "Katkı Tutar...",
    "goals.noGoals": "Henüz belirlenmiş hedef bulunmuyor.",
    "goals.noGoalsDesc": "Yandaki formu kullanarak hayal ettiğiniz birikim hedefini hemen oluşturun!",

    // Reports Additional
    "reports.downloadDescription": "Bu döneme ait mali verileri yüksek çözünürlüklü A4 PDF belgesi veya Türkçe karakter uyumlu Excel/CSV tablosu olarak indirin.",
    "reports.downloadCSV": "Excel (CSV) Raporu İndir",
    "reports.printPDF": "PDF Raporu Oluştur (Yazdır)",

    // Chart Additional
    "chart.cashFlowTitle": "Gelişmiş Nakit Akışı Öngörüsü",
    "chart.cashFlowDesc": "Sabit planlamalar ve geçmiş değişken harcama alışkanlıklarına göre 6 aylık akış tahmini.",
    "chart.trendAnalysisActive": "Tüm Geçmiş Trend Analizi Aktif",
    "chart.criticalBalanceLimit": "Kritik Bakiye Sınırı",
    "chart.criticalBalanceTooltip": "Bakiyeniz bu limitin altına indiğinde grafik ve uyarı afişi sizi uyarır.",
    "chart.balanceDropWarningTitle": "Bakiye Düşüş Uyarısı",
    "chart.balanceWarningDesc": "Cari tahmin gidişatınızda bakiyeniz, {months} aylarında belirlediğiniz kritik limit olan {limit} altına düşüyor! Finansal tedbir almayı düşünebilirsiniz.",
    "chart.simulatedBalanceDropWarningTitle": "Simüle Bakiye Düşüş Uyarısı",
    "chart.simulatedBalanceWarningDesc": "Eklediğiniz simülasyon senaryosuna göre bakiyeniz, {months} aylarında kritik sınırın altına geriliyor.",
    "chart.visibleSeries": "Grafikte Gösterilecek Veriler",
    "chart.projectedBalance": "Tahmini Bakiye",
    "chart.projectedIncome": "Beklenen Gelir",
    "chart.projectedExpense": "Beklenen Gider",
    "chart.simulatedBalance": "Simüle Bakiye",
    "chart.calcExplanationTitle": "Değişken Gider & Gelir Analizi Nasıl Hesaplanır?",
    "chart.calcExplanationDesc": "Girdiğiniz tüm geçmiş ({months} ay) veriler taranarak, her ay yinelenen sabit işlemleriniz ayıklandıktan sonra kalan değişken gelir/giderlerinizin aylık ortalaması alınır ve tahmin modeline dahil edilir.",
    "chart.avgVarIncome": "Ort. Değişken Gelir",
    "chart.avgVarExpense": "Ort. Değişken Gider",
    "chart.simTitle": "\"Ya Şöyle Olursa?\" Senaryo Simülasyonu",
    "chart.simReset": "Senaryoyu Sıfırla",
    "chart.simDesc": "Gelecek 6 aya ait tahmini gelir veya gider senaryoları ekleyerek bakiyenizin nasıl etkileneceğini anlık olarak grafikte gözlemleyin. Eklediğiniz işlemler geçicidir ve veri tabanına kaydedilmez.",
    "chart.simTargetMonth": "Hedef Ay",
    "chart.simIncomeOption": "Gelir (+)",
    "chart.simExpenseOption": "Gider (-)",
    "chart.simAmountLabel": "Tutar ({symbol})",
    "chart.simAmountPlaceholder": "Örn: 25000",
    "chart.simDescPlaceholder": "Örn: Yeni sözleşme, prim",
    "chart.simAddBtnTooltip": "İşlem Ekle",
    "chart.savingsAnalysisTitle": "Tasarruf Hedefleri & Nakit Akışı Uyumluluk Analizi",
    "chart.savingsAnalysisDesc": "Gelecek 6 aylık tahmini nakit akışınıza göre, aktif hedeflerinize vade tarihlerinde ulaşıp ulaşamayacağınız analiz edilmiştir.",
    "chart.statusFeasible": "Ulaşılabilir",
    "chart.statusAtRisk": "Risk Altında",
    "chart.statusOverdue": "Süresi Geçmiş",
    "chart.statusLongTerm": "Uzun Vadeli",
    "chart.remainingGoalAmount": "Kalan Hedef Tutar:",
    "chart.dueDateLabel": "Vade Tarihi:",
    "chart.descFeasible": "Vade ayında ({month}) öngörülen kasanız {balance}, kalan hedefinizden fazla. Bu hedefi rahatlıkla karşılayabilirsiniz.",
    "chart.descAtRisk": "Vade ayında ({month}) kasanızın {balance} olması öngörülüyor. Hedefi tamamlamak için {deficit} açığınız kalabilir.",
    "chart.suggestedContribution": "Katkı Önerisi: Kalan {months} ay boyunca her ay ortalama en az {amount} ek tasarruf yapmanız veya simülasyona ek gelir senaryosu eklemeniz önerilir.",
    "chart.descOverdue": "Hedefinizin vadesi geçmiş durumda. Hedef tarihini güncelleyerek yeniden analiz alabilirsiniz.",
    "chart.descLongTerm": "Hedef vadeniz 6 aydan uzun olduğu için nakit akışı grafiğinde doğrudan analiz edilmemiştir.",
    "chart.noSimulatedItems": "Henüz simüle edilmiş işlem bulunmuyor. Yukarıdaki formdan ekleyebilirsiniz.",
    "chart.simIncomeDefault": "Simüle Gelir",
    "chart.simExpenseDefault": "Simüle Gider",
    "chart.monthlyComparisonTitle": "Aylık Karşılaştırmalı Trend",
    "chart.yearlyIncome": "Yıllık Gelir",
    "chart.yearlyExpense": "Yıllık Gider",
    "chart.net": "Net",
    "chart.noDataForYear": "{year} yılı için henüz gelir veya gider verisi bulunmuyor.",

    // Category Translation
    "category.Maaş": "Maaş",
    "category.Ek Gelir": "Ek Gelir",
    "category.Yatırım": "Yatırım",
    "category.Kira": "Kira",
    "category.Market": "Market",
    "category.Ulaşım": "Ulaşım",
    "category.Faturalar": "Faturalar",
    "category.Sağlık": "Sağlık",
    "category.Eğlence": "Eğlence",
    "category.Diğer": "Diğer",

    // Recurring Transaction Manager
    "rec.noDescription": "Açıklamasız Sabit İşlem",
    "rec.monthlyDay": "Her Ayın {day}'i",
    "rec.uncategorized": "Kategorisiz",
    "rec.deleteTitle": "Sabit İşlemi Sil",
    "rec.deleteDesc": "Bu sabit işlemi silmek istediğinizden emin misiniz? Artık bu işlem her ay otomatik olarak eklenmeyecektir.",

    // Print Report
    "print.title": "Mali Durum Raporu",
    "print.project": "Şirket / Proje:",
    "print.period": "Dönem:",
    "print.reportDate": "Raporlama Tarihi:",
    "print.incomeDistribution": "Gelir Kategori Dağılımı",
    "print.noIncome": "Bu dönemde gelir bulunmuyor.",
    "print.expenseDistribution": "Gider Kategori Dağılımı",
    "print.noExpense": "Bu dönemde gider bulunmuyor.",
    "print.detailedList": "Detaylı İşlem Listesi ({count} İşlem)",
    "print.noDescription": "Açıklama yok",
    "print.noTransactions": "Bu dönemde yapılmış bir işlem bulunamadı.",
    "print.generatedBy": "Gelir Gider Takip Sistemi tarafından otomatik üretilmiştir.",
    "print.generatedSub": "Güvenli ve şifreli yerel finansal veri yöneticisi.",
    "print.signature": "İmza / Kaşe",

    // Budget Tracking
    "cat.budgetTrackingTitle": "Aylık Bütçe Takip Limitleri",
    "cat.spentLabel": "Harcama",
    "cat.limitLabel": "Limit",

    // Update Notifications
    "update.checking": "Yeni sürümler kontrol ediliyor...",
    "update.found": "Yeni sürüm ({version}) bulundu! İndiriliyor...",
    "update.downloaded": "Yeni sürüm (v{version}) başarıyla indirildi. Yüklemek ve güncel sürümü başlatmak için tıklayın.",
    "update.btn": "Güncelle ve Yeniden Başlat",
    "update.readyTitle": "Yeni Güncelleme Hazır!",
    "update.mobileAvailable": "Yeni bir mobil güncelleme mevcut:",
  },
  en: {
    // Navigation / Tabs
    "nav.home": "Dashboard",
    "nav.reports": "Reports",
    "nav.chequesNotes": "Cheques & Notes",
    "nav.settings": "Settings",
    "nav.title": "Expense Tracker",
    "nav.transactions": "Transactions",
    "nav.goals": "Goals",
    "nav.viewAllProjects": "View All Companies",
    "nav.allProjects": "All Companies",
    "nav.subTitle": "Your personal finance manager",
    "summary.totalBalance": "Total Balance",

    // General Words
    "general.income": "Income",
    "general.expense": "Expense",
    "general.amount": "Amount",
    "general.description": "Description",
    "general.category": "Category",
    "general.date": "Date",
    "general.paymentMethod": "Payment Method",
    "general.project": "Company / Project",
    "general.none": "Not Specified",
    "general.cash": "Cash",
    "general.creditCard": "Credit Card",
    "general.actions": "Actions",
    "general.save": "Save",
    "general.cancel": "Cancel",
    "general.delete": "Delete",
    "general.edit": "Edit",
    "general.active": "Active",
    "general.passive": "Passive",
    "general.loading": "Loading...",
    "general.search": "Search transactions...",
    "general.all": "All",
    "general.personal": "Personal (Non-Company)",
    "general.required": "This field is required",
    "general.success": "Success",
    "general.error": "Error",
    "general.type": "Type",
    "general.unknown": "Unknown",
    "general.currency": "Currency",
    "general.cashEmoji": "💵 Cash",
    "general.cardEmoji": "💳 Credit Card",
    "form.addIncome": "Add Income",
    "form.addExpense": "Add Expense",
    "form.selectDate": "Select Date",
    "form.descriptionOptional": "Description (Optional)",

    // Summary Cards
    "summary.totalIncome": "Total Income",
    "summary.totalExpense": "Total Expense",
    "summary.netBalance": "Net Balance",
    "summary.transactionCount": "Transactions",

    // Forms
    "form.addNewTransaction": "Add New Transaction",
    "form.editTransaction": "Edit Transaction",
    "form.editTransactionDesc": "Update the details of the selected transaction.",
    "form.mathHint": "0.00 or 100+50-20...",
    "form.selectCategory": "Select category",
    "form.selectPaymentMethod": "Select payment method",
    "form.selectProject": "Select company/project",
    "form.optional": "Optional",
    "form.notePlaceholder": "Transaction note...",
    "form.submitAdd": "Add",
    "form.quickTemplates": "Quick Templates",

    // Recurring Forms
    "form.addNewRecurring": "Add Recurring Transaction",
    "form.startDate": "Start Date",
    "form.endDate": "End Date",
    "form.hasEndDate": "Has end date",
    "form.isActive": "Active",
    "form.selectStartDate": "Select start date",
    "form.selectEndDate": "Select end date",
    "form.addRecurringIncome": "Add Recurring Income",
    "form.addRecurringExpense": "Add Recurring Expense",

    // Recurring Manager
    "rec.title": "Recurring Transactions",
    "rec.desc": "Manage your monthly recurring transactions like salary, rent, and subscriptions here. The system adds them automatically when their due dates arrive.",
    "rec.addNew": "New Recurring",
    "rec.activeState": "Status",
    "rec.noItems": "No recurring transactions defined yet.",
    "rec.addFirst": "Use the form above to create your first recurring transaction!",

    // Filter Bar
    "filter.viewMode": "View Mode",
    "filter.daily": "Daily",
    "filter.monthly": "Monthly",
    "filter.yearly": "Yearly",
    "filter.customRange": "Custom Date Range",
    "filter.minAmount": "Min Amount",
    "filter.maxAmount": "Max Amount",
    "filter.categories": "Categories",
    "filter.reset": "Clear Filters",
    "filter.advanced": "Advanced Filters",
    "month.jan": "January", "month.feb": "February", "month.mar": "March", "month.apr": "April", "month.may": "May", "month.jun": "June",
    "month.jul": "July", "month.aug": "August", "month.sep": "September", "month.oct": "October", "month.nov": "November", "month.dec": "December",
    "filter.view": "View:",
    "form.startDateShort": "Start",
    "form.endDateShort": "End",
    "filter.txDesc": "Transaction Description",
    "filter.searchPlaceholder": "Search in descriptions...",
    "filter.allMethods": "All Methods",
    "filter.cashOnly": "💵 Cash Only",
    "filter.cardOnly": "💳 Credit Card Only",
    "filter.amountRange": "Amount Range",
    "filter.clearSelection": "Clear Selection",
    "filter.resetAll": "Reset All Filters",

    // Charts
    "chart.monthlyTrend": "Income vs Expense Trend",
    "chart.cashFlow": "6-Month Cash Flow & Balance Forecast (Includes Recurring)",
    "chart.incomeDistribution": "Income Distribution",
    "chart.expenseDistribution": "Expense Distribution",
    "chart.companySummary": "Company Distribution Summary Report",
    "chart.noData": "No data available",

    // Cheques and Notes
    "cn.title": "Cheques & Promissory Notes",
    "cn.desc": "Record your receivable and payable cheques or notes, track their due dates, and transfer them to transactions with a single click.",
    "cn.addNew": "Add New Cheque/Note",
    "cn.cheque": "Cheque",
    "cn.promissoryNote": "Promissory Note",
    "cn.receivable": "Receivable",
    "cn.payable": "Payable",
    "cn.debtor": "Debtor / Payer",
    "cn.bank": "Bank / Branch",
    "cn.serial": "Serial Number",
    "cn.dueDate": "Due Date",
    "cn.issueDate": "Issue Date",
    "cn.status": "Status",
    "cn.pending": "Pending",
    "cn.paid": "Collected / Paid",
    "cn.cancelled": "Cancelled",
    "cn.returned": "Returned / Bounced",
    "cn.noItems": "No cheques or notes recorded yet.",
    "cn.createTransaction": "Transfer to Transactions",
    "cn.transferred": "Transferred to transactions successfully.",
    "cn.reminderTitle": "Cheques & Notes Reminder",
    "cn.reminderDesc": "Manage your post-dated receivable and payable documents.",
    "cn.totalReceivables": "Total Receivables",
    "cn.pendingCollections": "Pending collections",
    "cn.totalPayables": "Total Payables",
    "cn.pendingPayments": "Pending payments",
    "cn.dueOverdue": "Due / Overdue",
    "cn.itemsCount": "{count} Items",
    "cn.totalPrefix": "Total: ",
    "cn.searchPlaceholder": "Search debtor, serial no or description...",
    "cn.allDocs": "All Documents",
    "cn.allDirections": "All Directions",
    "cn.allStatuses": "All Statuses",
    "cn.collectedPaidStatus": "Collected/Paid",
    "cn.bouncedReturnedStatus": "Bounced/Returned",
    "cn.docDetail": "Document Detail",
    "cn.serialBank": "Serial No / Bank",
    "cn.dueIssue": "Due / Issue",
    "cn.bankNotSpecified": "Bank not specified",
    "cn.overdueLabel": "Overdue",
    "cn.todayLabel": "Today!",
    "cn.duePrefix": "Due: ",
    "cn.issuePrefix": "Issue: ",
    "cn.markPaidTooltip": "Mark as Collected / Paid",
    "cn.debtorCreditor": "Debtor/Creditor",
    "cn.addNewDoc": "Add New Cheque / Note",
    "cn.addNewDocTitle": "Add New Cheque or Note",
    "cn.addNewDocDesc": "Enter details of the post-dated document.",
    "cn.docType": "Document Type",
    "cn.selectPlaceholder": "Select",
    "cn.docDirection": "Direction",
    "cn.receivableReceived": "Receivable (Received)",
    "cn.payableIssued": "Payable (Issued)",
    "cn.amountTL": "Amount (TL)",
    "cn.serialPlaceholder": "Cheque/Note Serial No...",
    "cn.issueDateLabel": "Issue / Settlement Date",
    "cn.debtorPlaceholder": "Name / Company...",
    "cn.bankPlaceholder": "Garanti, Akbank etc...",
    "cn.relatedProject": "Related Company / Project",
    "cn.selectCompanyOptional": "Select Company (Optional)",
    "cn.noAssociation": "No Association",
    "cn.notesPlaceholder": "Enter additional notes...",
    "cn.editDocTitle": "Edit Document",
    "cn.editDocDesc": "Edit the details of the selected document.",
    "cn.docStatus": "Document Status",
    "cn.selectStatus": "Select Status",
    "cn.cancelledStatusFull": "Cancelled",
    "cn.returnedStatusFull": "Bounced/Returned",
    "cn.updateStatusTitle": "Update {type} Status",
    "cn.updateStatusDesc": "You are about to mark this document as Collected / Paid.",
    "cn.docDetailsTitle": "Document Details",
    "cn.autoRecordLedger": "Automatically record to ledger as income/expense",
    "cn.ledgerCategory": "Category for Transaction",
    "cn.dismissBtn": "Cancel",
    "cn.confirmPaymentBtn": "Collect / Mark Paid",
    "cn.deleteTitle": "Delete Record",
    "cn.deleteDesc": "Are you sure you want to delete this cheque/note record? This action cannot be undone.",
    "cn.deleteConfirmBtn": "Yes, Delete",

    // Settings
    "settings.title": "Application Settings",
    "settings.theme": "Theme Mode",
    "settings.themeLight": "Light Theme",
    "settings.themeDark": "Dark Theme",
    "settings.themeSystem": "System Default",
    "settings.currency": "Default Currency",
    "currency.try": "Turkish Lira (₺ - TRY)",
    "currency.usd": "US Dollar ($ - USD)",
    "currency.eur": "Euro (€ - EUR)",
    "currency.gbp": "British Pound (£ - GBP)",
    "settings.autoLock": "Auto Lock Timeout",
    "settings.autoLockDisabled": "Disabled (Do not lock)",
    "settings.autoLockMin": "{min} Minutes Inactivity",
    "settings.autoLockDesc": "The screen locks automatically after a period of inactivity. (Works only when password protection is active)",
    "settings.language": "Language / Dil",

    // Backup and Cloud
    "settings.backupTitle": "Local Backup & Restore",
    "settings.backupDesc": "You can backup your local data as a JSON file to your computer or restore your data from a previously created backup file.",
    "settings.backupExport": "Export Backup (JSON)",
    "settings.backupImport": "Import Backup (JSON)",
    "settings.cloudTitle": "Cloud Synchronization",
    "settings.cloudDesc": "Log in to safely store your data in the cloud and synchronize it with your other devices.",
    "settings.cloudDelete": "Delete Cloud Data",
    "settings.cloudDeleteConfirm": "Type 'ONAYLIYORUM' to delete all your cloud data:",

    // Encryption / Password Settings
    "settings.passTitle": "Screen Lock & Encryption",
    "settings.passDesc": "Protect your local data by adding a password lock on application startup.",
    "settings.passEnable": "Enable Password Protection",
    "settings.passDisable": "Disable Password Protection",

    "general.downloadCSV": "Download CSV",
    "list.noItems": "No transactions found matching your criteria.",
    "form.paymentMethodOptional": "Payment Method (Optional)",
    "list.deleteTransaction": "Delete Transaction",
    "list.deleteConfirm": "Are you sure you want to delete this transaction? This action cannot be undone.",

    // Toasts and Dialogs
    "toast.saved": "Saved successfully.",
    "toast.updated": "Updated successfully.",
    "toast.deleted": "Deleted successfully.",
    "toast.error": "An error occurred.",
    "toast.backupSuccess": "Backup loaded successfully.",
    "toast.currencySet": "Default currency set to {val}.",
    "toast.languageSet": "Language set to English.",
    "toast.syncSuccess": "Cloud sync completed successfully.",
    "toast.connectionRestored": "Internet connection restored, uploading pending changes...",
    "toast.newerDataFound": "Newer data detected in the cloud, your data has been synchronized.",
    "toast.deleteCancelled": "Data deletion cancelled because it was not confirmed.",
    "toast.dataCleared": "Your cloud and local data have been cleared successfully.",
    "toast.cloudSynced": "Your up-to-date cloud data has been synchronized.",
    "toast.localNewer": "Your local data is newer than cloud, uploading changes...",
    "toast.realtimeSynced": "New data from another device has been synchronized.",
    "cloud.deleteSuccess": "Your cloud and local data have been permanently deleted. You have been logged out.",
    "cloud.deleteFailed": "Could not delete account data.",
    "proj.selectLaunchTitle": "Select Company / Project",
    "proj.selectLaunchDesc": "Select the company you want to log in and manage income/expenses for:",
    "general.addTransaction": "Add Transaction",
    "general.single": "One-time",
    "general.recurring": "Recurring",
    "toast.fillFields": "Please fill in all required fields with valid values.",
    "toast.invalidContribution": "Please enter a valid contribution amount.",
    "toast.contributionSuccess": "Contribution added to the savings target successfully.",
    "login.verifying": "Verifying session...",
    "changelog.title": "New Update: v1.1.4",
    "changelog.subtitle": "Expense Tracker has been updated!",
    "changelog.desc": "We brought multi-currency support and advanced Excel/CSV reporting features. Here are the features introduced in v1.1.4:",
    "changelog.multiCurrency": "Multi-Currency Support",
    "changelog.multiCurrencyDesc": "Transaction-based currency selection (TRY, USD, EUR) is added. All your financial summaries, charts, and forecasts are automatically calculated in your selected default currency.",
    "changelog.liveRates": "Live Exchange Rates",
    "changelog.liveRatesDesc": "The latest rates are automatically fetched online on startup, ensuring instant and accurate balance conversions. Safe default rates are used when offline.",
    "changelog.export": "Excel (CSV) Export",
    "changelog.exportDesc": "From the Reports tab, you can export all your transaction histories to Excel (CSV) with a single click, fully compatible with Turkish characters and UTF-8 BOM.",
    "changelog.fixes": "Bug Fixes & Chart Adjustments",
    "changelog.fixesDesc": "The dashed visual line error on the cash flow forecast chart is resolved, and filter sync for goals templates has been perfected.",

    // Category Manager
    "cat.title": "Categories",
    "cat.new": "New",
    "cat.incomeTitle": "Income Categories",
    "cat.expenseTitle": "Expense Categories",
    "cat.editTitle": "Edit Category",
    "cat.addTitle": "Add New Category",
    "cat.editDesc": "Update the details of the category.",
    "cat.addDesc": "Create a new income or expense category.",
    "cat.nameLabel": "Category Name",
    "cat.namePlaceholder": "e.g. Groceries, Transport...",
    "cat.typeLabel": "Type",
    "cat.budgetLimit": "Monthly Budget Limit ({symbol}) (Optional)",
    "cat.budgetPlaceholder": "e.g. 5000",
    "cat.budgetDesc": "Sets a maximum monthly spending limit for this category.",
    "cat.colorLabel": "Color",
    "cat.updateBtn": "Update",
    "cat.addBtn": "Add",
    "cat.deleteTitle": "Delete Category",
    "cat.deleteDesc": "Are you sure you want to delete this category? Transactions belonging to this category will automatically be reassigned to the **\"Other\"** category.",
    "cat.other": "Other",
    "cat.limitShort": "L",

    // Project Manager
    "proj.title": "Companies / Projects",
    "proj.new": "New",
    "proj.all": "All Companies",
    "proj.empty": "No companies/projects added yet",
    "proj.passive": "Passive",
    "proj.editTitle": "Edit Company/Project",
    "proj.addTitle": "Add New Company/Project",
    "proj.editDesc": "Update company or project details.",
    "proj.addDesc": "Create a new company or project.",
    "proj.nameLabel": "Name",
    "proj.namePlaceholder": "e.g. Main Company, Project A...",
    "proj.descLabel": "Description (Optional)",
    "proj.descPlaceholder": "Brief information about company/project...",
    "proj.colorLabel": "Color",
    "proj.activeLabel": "Active",
    "proj.deleteTitle": "Delete Company/Project",
    "proj.deleteDesc": "Are you sure you want to delete this company/project? Transactions associated with it will lose their association.",

    // Password Protection
    "pass.lockedTitle": "Application Locked",
    "pass.enterPass": "Enter your password to access the application",
    "pass.placeholder": "Your password",
    "pass.errorInvalid": "Incorrect password or data could not be decrypted",
    "pass.errorGeneral": "An error occurred",
    "pass.unlocking": "Decrypting...",
    "pass.unlockBtn": "Unlock",
    "pass.forgotBtn": "Forgot Password",
    "pass.resetTitle": "Reset Password",
    "pass.resetDesc": "To reset your password, you need to sign in again with your Google account. <br /><br /><strong class=\"text-amber-600 dark:text-amber-400\">Important Warning:</strong> Since your password is forgotten, your encrypted local data cannot be decrypted and will be cleared from this device. After signing in with Google, your cloud data (Supabase) will be automatically restored.<br /><br />Your current session will be closed and you will be redirected to the Google login page. Make sure you have an internet connection.",
    "pass.resetConfirmBtn": "Yes, Log Out and Reset",
    "pass.settingsTitle": "Password Protection",
    "pass.statusActive": "Password protection active (Data is stored encrypted on disk)",
    "pass.removeBtn": "Disable Password Protection",
    "pass.newLabel": "New Password",
    "pass.newPlaceholder": "At least 4 characters",
    "pass.confirmLabel": "Confirm Password",
    "pass.confirmPlaceholder": "Enter password again",
    "pass.settingUp": "Setting up...",
    "pass.setupBtn": "Set Password",
    "pass.errorShort": "Password must be at least 4 characters",
    "pass.errorMismatch": "Passwords do not match",
    "pass.successSet": "Password set successfully. Your data has been encrypted locally.",
    "pass.errorSet": "An error occurred while setting the password.",
    "pass.successRemove": "Password protection disabled. Your data is now stored unencrypted.",
    "pass.errorRemove": "An error occurred while disabling password protection.",
    "pass.hint": "When password protection is enabled, you will be prompted for a password on each startup, and all local data will be stored encrypted.",

    // Cloud Sync
    "cloud.title": "Cloud Synchronization",
    "cloud.notConfigured": "Supabase not configured (check .env file).",
    "cloud.loading": "Cloud operation in progress...",
    "cloud.success": "Cloud operation successful.",
    "cloud.error": "Cloud operation failed.",
    "cloud.offline": "You are offline.",
    "cloud.connected": "Connected to cloud.",
    "cloud.envMissing": "Supabase settings are missing. Please add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to your .env file.",
    "cloud.googleUser": "Google User",
    "cloud.offlineError": "You are offline. It will synchronize automatically when connection is restored.",
    "cloud.downloadError": "Could not download data.",
    "cloud.signOut": "Sign Out",
    "cloud.deleteTitle": "Delete Cloud Data",
    "cloud.deleteDesc": "This action deletes your data from the cloud and logs you out.",
    "cloud.deletePrompt": "Are you sure you want to permanently delete your account data from the cloud and local storage?\n\nThis action cannot be undone. To confirm, type 'ONAYLIYORUM' in the box:",
    "cloud.deleteBtn": "Delete Cloud Data",
    "cloud.online": "Online",
    "cloud.offlineBadge": "Offline",
    "cloud.syncPending": "Sync Pending",
    "cloud.uploadBtn": "Upload to Cloud",
    "cloud.downloadBtn": "Download from Cloud",
    "cloud.hint": "Your data is stored on Supabase linked to your user account. It can continue to be kept locally on your device if you prefer; uploading and downloading are entirely under your control.",

    // Google Login
    "login.title": "Expense Tracker",
    "login.subtitle": "Sign in with your Google account to continue",
    "login.btn": "Sign in with Google",
    "login.hint": "When you sign in, your data is securely synchronized in the cloud.",
    "login.envMissing": "Supabase not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to your .env file.",

    // General Additional
    "general.add": "Add",
    "general.showHide": "Show/Hide",
    "general.total": "Total",
    "general.prediction": "Forecast",

    // Transactions Additional
    "transactions.selectedPeriodTransactions": "Selected Period Transactions",
    "transactions.dailyTransactions": "Daily Transactions",
    "transactions.monthlyTransactions": "Monthly Transactions",
    "transactions.yearlyTransactions": "Yearly Transactions",

    // Goals Additional
    "goals.newGoal": "Set New Goal",
    "goals.nameLabel": "Goal Name *",
    "goals.namePlaceholder": "e.g. New Computer, Vacation...",
    "goals.targetLabel": "Target Amount ({symbol}) *",
    "goals.targetPlaceholder": "e.g. 50000",
    "goals.dateLabel": "Goal Date *",
    "goals.projectAssociation": "Company / Project Association",
    "goals.personalOption": "🏢 Personal (Non-Company)",
    "goals.saveGoal": "Save Goal",
    "goals.activeGoals": "🎯 Your Active Financial Goals",
    "goals.totalGoals": "Total: {count} Goals",
    "goals.completedBadge": "Completed 🎉",
    "goals.deleteGoal": "Delete Goal",
    "goals.progressLabel": "Progress: {progress}%",
    "goals.dueDate": "Due Date:",
    "goals.daysLeft": "{count} days left",
    "goals.overdue": "Overdue",
    "goals.remainingAmount": "Remaining Amount:",
    "goals.contributionPlaceholder": "Contribution Amount...",
    "goals.noGoals": "No goals set yet.",
    "goals.noGoalsDesc": "Use the form on the left to set your savings target!",

    // Reports Additional
    "reports.downloadDescription": "Download financial data for this period as a high-resolution A4 PDF document or a compatible Excel/CSV sheet.",
    "reports.downloadCSV": "Download Excel (CSV) Report",
    "reports.printPDF": "Generate PDF Report (Print)",

    // Chart Additional
    "chart.cashFlowTitle": "Advanced Cash Flow Forecast",
    "chart.cashFlowDesc": "6-month flow forecast based on recurring transactions and historical variable spending habits.",
    "chart.trendAnalysisActive": "All Historical Trend Analysis Active",
    "chart.criticalBalanceLimit": "Critical Balance Limit",
    "chart.criticalBalanceTooltip": "The chart and warning banner will alert you if your balance dips below this limit.",
    "chart.balanceDropWarningTitle": "Balance Dip Warning",
    "chart.balanceWarningDesc": "In your current projected forecast, your balance dips below your critical limit of {limit} in {months}! You may want to take financial precautions.",
    "chart.simulatedBalanceDropWarningTitle": "Simulated Balance Dip Warning",
    "chart.simulatedBalanceWarningDesc": "According to your added simulation scenarios, your balance falls below the critical limit in {months}.",
    "chart.visibleSeries": "Data to Display on Chart",
    "chart.projectedBalance": "Projected Balance",
    "chart.projectedIncome": "Expected Income",
    "chart.projectedExpense": "Expected Expense",
    "chart.simulatedBalance": "Simulated Balance",
    "chart.calcExplanationTitle": "How is Variable Expense & Income Analysis Calculated?",
    "chart.calcExplanationDesc": "All your past ({months} months) data is scanned, recurring transactions are filtered out, and the monthly average of remaining variable income/expenses is calculated and included in the forecasting model.",
    "chart.avgVarIncome": "Avg. Variable Income",
    "chart.avgVarExpense": "Avg. Variable Expense",
    "chart.simTitle": "\"What If?\" Scenario Simulation",
    "chart.simReset": "Reset Scenario",
    "chart.simDesc": "Observe the instant impact on your balance by adding estimated income or expense scenarios for the next 6 months. These added transactions are temporary and not saved to the database.",
    "chart.simTargetMonth": "Target Month",
    "chart.simIncomeOption": "Income (+)",
    "chart.simExpenseOption": "Expense (-)",
    "chart.simAmountLabel": "Amount ({symbol})",
    "chart.simAmountPlaceholder": "e.g. 25000",
    "chart.simDescPlaceholder": "e.g. New contract, bonus",
    "chart.simAddBtnTooltip": "Add Transaction",
    "chart.savingsAnalysisTitle": "Savings Goals & Cash Flow Feasibility Analysis",
    "chart.savingsAnalysisDesc": "Based on your projected 6-month cash flow, we analyzed whether you can achieve your active goals on their due dates.",
    "chart.statusFeasible": "Achievable",
    "chart.statusAtRisk": "At Risk",
    "chart.statusOverdue": "Overdue",
    "chart.statusLongTerm": "Long Term",
    "chart.remainingGoalAmount": "Remaining Goal Amount:",
    "chart.dueDateLabel": "Due Date:",
    "chart.descFeasible": "In the target month ({month}), your projected balance ({balance}) is greater than your remaining goal. You can easily afford this goal.",
    "chart.descAtRisk": "In the target month ({month}), your balance is projected to be {balance}. You might have a deficit of {deficit} to complete the goal.",
    "chart.suggestedContribution": "Suggested Contribution: It is recommended to save at least {amount} more each month for the remaining {months} months or add an additional income scenario to the simulation.",
    "chart.descOverdue": "Your goal's target date has passed. You can update the target date to run the analysis again.",
    "chart.descLongTerm": "Because your goal's target date is longer than 6 months, it is not directly analyzed in the cash flow chart.",
    "chart.noSimulatedItems": "No simulated transactions yet. You can add one using the form above.",
    "chart.simIncomeDefault": "Simulated Income",
    "chart.simExpenseDefault": "Simulated Expense",
    "chart.monthlyComparisonTitle": "Monthly Comparison Trend",
    "chart.yearlyIncome": "Yearly Income",
    "chart.yearlyExpense": "Yearly Expense",
    "chart.net": "Net",
    "chart.noDataForYear": "No income or expense data available for {year}.",

    // Category Translation
    "category.Maaş": "Salary",
    "category.Ek Gelir": "Extra Income",
    "category.Yatırım": "Investment",
    "category.Kira": "Rent",
    "category.Market": "Groceries",
    "category.Ulaşım": "Transportation",
    "category.Faturalar": "Bills",
    "category.Sağlık": "Health",
    "category.Eğlence": "Entertainment",
    "category.Diğer": "Other",

    // Recurring Transaction Manager
    "rec.noDescription": "Untitled Recurring Transaction",
    "rec.monthlyDay": "Day {day} of Month",
    "rec.uncategorized": "Uncategorized",
    "rec.deleteTitle": "Delete Recurring Transaction",
    "rec.deleteDesc": "Are you sure you want to delete this recurring transaction? It will no longer be added automatically each month.",

    // Print Report
    "print.title": "Financial Status Report",
    "print.project": "Company / Project:",
    "print.period": "Period:",
    "print.reportDate": "Report Date:",
    "print.incomeDistribution": "Income Category Distribution",
    "print.noIncome": "No income recorded in this period.",
    "print.expenseDistribution": "Expense Category Distribution",
    "print.noExpense": "No expenses recorded in this period.",
    "print.detailedList": "Detailed Transaction List ({count} Transactions)",
    "print.noDescription": "No description",
    "print.noTransactions": "No transactions found in this period.",
    "print.generatedBy": "Automatically generated by the Expense Tracker System.",
    "print.generatedSub": "Secure and encrypted local financial data manager.",
    "print.signature": "Signature / Stamp",

    // Budget Tracking
    "cat.budgetTrackingTitle": "Monthly Budget Tracking Limits",
    "cat.spentLabel": "Spent",
    "cat.limitLabel": "Limit",

    // Update Notifications
    "update.checking": "Checking for updates...",
    "update.found": "New version ({version}) found! Downloading...",
    "update.downloaded": "New version (v{version}) downloaded successfully. Click to install and restart.",
    "update.btn": "Update and Restart",
    "update.readyTitle": "New Update Ready!",
    "update.mobileAvailable": "A new mobile update is available:",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('gelir-gider-language') as Language) || 'tr';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('gelir-gider-language', lang);
  };

  const t = (key: string, replacements?: Record<string, string | number>, fallback?: string): string => {
    const dict = translations[language];
    let value = (dict as any)[key] || fallback || key;

    if (replacements) {
      Object.entries(replacements).forEach(([k, v]) => {
        value = value.replace(`{${k}}`, String(v));
      });
    }

    return value;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
