import React, { createContext, useContext, useState } from 'react';

type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, replacements?: Record<string, string | number>) => string;
}

const translations = {
  tr: {
    // Navigation / Tabs
    "nav.home": "Ana Sayfa",
    "nav.reports": "Raporlar",
    "nav.chequesNotes": "Çek & Senet",
    "nav.settings": "Ayarlar",
    "nav.title": "Gelir Gider Takip",
    "nav.transactions": "İşlemler",
    "nav.goals": "Hedefler",
    "nav.viewAllProjects": "Tüm Şirketleri Görüntüle",
    "nav.allProjects": "Tüm Şirketler",
    "nav.subTitle": "Kişisel finans yöneticiniz",
    "summary.totalBalance": "Toplam Bakiye",

    // General Words
    "general.income": "Gelir",
    "general.expense": "Gider",
    "general.amount": "Tutar",
    "general.description": "Açıklama",
    "general.category": "Kategori",
    "general.date": "Tarih",
    "general.paymentMethod": "Ödeme Yöntemi",
    "general.project": "Şirket / Proje",
    "general.none": "Belirtilmemiş",
    "general.cash": "Nakit",
    "general.creditCard": "Kredi Kartı",
    "general.actions": "İşlemler",
    "general.save": "Kaydet",
    "general.cancel": "İptal",
    "general.delete": "Sil",
    "general.edit": "Düzenle",
    "general.active": "Aktif",
    "general.passive": "Pasif",
    "general.loading": "Yükleniyor...",
    "general.search": "İşlemlerde ara...",
    "general.all": "Tümü",
    "general.personal": "Kişisel (Şirket Dışı)",
    "general.required": "Bu alan zorunludur",
    "general.success": "Başarılı",
    "general.error": "Hata",
    "general.type": "Tür",
    "general.unknown": "Bilinmeyen",
    "general.currency": "Döviz",
    "general.cashEmoji": "💵 Nakit",
    "general.cardEmoji": "💳 Kredi Kartı",
    "form.addIncome": "Gelir Ekle",
    "form.addExpense": "Gider Ekle",
    "form.selectDate": "Tarih seçin",
    "form.descriptionOptional": "Açıklama (Opsiyonel)",

    // Summary Cards
    "summary.totalIncome": "Toplam Gelir",
    "summary.totalExpense": "Toplam Gider",
    "summary.netBalance": "Net Bakiye",
    "summary.transactionCount": "İşlem Sayısı",

    // Forms
    "form.addNewTransaction": "Yeni İşlem Ekle",
    "form.editTransaction": "İşlemi Düzenle",
    "form.editTransactionDesc": "Seçili işlemin detaylarını güncelleyin.",
    "form.mathHint": "0.00 veya 100+50-20...",
    "form.selectCategory": "Kategori seçin",
    "form.selectPaymentMethod": "Ödeme yöntemi seçin",
    "form.selectProject": "Şirket/Proje seçin",
    "form.optional": "Opsiyonel",
    "form.notePlaceholder": "İşlem hakkında not...",
    "form.submitAdd": "Ekle",
    "form.quickTemplates": "Hızlı Şablonlar",
    
    // Recurring Forms
    "form.addNewRecurring": "Sabit İşlem Ekle",
    "form.startDate": "Başlangıç Tarihi",
    "form.endDate": "Bitiş Tarihi",
    "form.hasEndDate": "Bitiş tarihi var",
    "form.isActive": "Aktif",
    "form.selectStartDate": "Başlangıç tarihi seçin",
    "form.selectEndDate": "Bitiş tarihi seçin",
    "form.addRecurringIncome": "Sabit Gelir Ekle",
    "form.addRecurringExpense": "Sabit Gider Ekle",

    // Recurring Manager
    "rec.title": "Sabit İşlemler",
    "rec.desc": "Maaş, kira, abonelik gibi her ay düzenli tekrarlanan işlemlerinizi buradan yönetin. Sistem bu işlemleri vadesi geldikçe otomatik olarak ekler.",
    "rec.addNew": "Yeni Sabit İşlem",
    "rec.activeState": "Durum",
    "rec.noItems": "Henüz tanımlanmış sabit işlem bulunmuyor.",
    "rec.addFirst": "Yukarıdaki formu kullanarak ilk sabit işleminizi oluşturun!",

    // Filter Bar
    "filter.viewMode": "Görünüm Modu",
    "filter.daily": "Günlük",
    "filter.monthly": "Aylık",
    "filter.yearly": "Yıllık",
    "filter.customRange": "Özel Tarih Aralığı",
    "filter.minAmount": "Min Tutar",
    "filter.maxAmount": "Max Tutar",
    "filter.categories": "Kategoriler",
    "filter.reset": "Filtreleri Temizle",
    "filter.advanced": "Gelişmiş Filtreler",
    "month.jan": "Ocak", "month.feb": "Şubat", "month.mar": "Mart", "month.apr": "Nisan", "month.may": "Mayıs", "month.jun": "Haziran",
    "month.jul": "Temmuz", "month.aug": "Ağustos", "month.sep": "Eylül", "month.oct": "Ekim", "month.nov": "Kasım", "month.dec": "Aralık",
    "filter.view": "Görünüm:",
    "form.startDateShort": "Başlangıç",
    "form.endDateShort": "Bitiş",
    "filter.txDesc": "İşlem Açıklaması",
    "filter.searchPlaceholder": "Açıklamalarda ara...",
    "filter.allMethods": "Tüm Yöntemler",
    "filter.cashOnly": "💵 Sadece Nakit",
    "filter.cardOnly": "💳 Sadece Kredi Kartı",
    "filter.amountRange": "Tutar Aralığı",
    "filter.clearSelection": "Seçimi Temizle",
    "filter.resetAll": "Tüm Filtreleri Sıfırla",

    // Charts
    "chart.monthlyTrend": "Gelir vs Gider Dağılımı",
    "chart.cashFlow": "6 Aylık Nakit Akışı ve Bakiye Tahmini (Sabit İşlemler Dahil)",
    "chart.incomeDistribution": "Gelir Dağılımı",
    "chart.expenseDistribution": "Gider Dağılımı",
    "chart.companySummary": "Şirket Dağılımı Özet Raporu",
    "chart.noData": "Veri bulunmuyor",

    // Cheques and Notes
    "cn.title": "Çek ve Senet Yönetimi",
    "cn.desc": "Alacak ve borç çek/senetlerinizi kaydedin, vadelerini takip edin ve günü geldiğinde tek tıklamayla işlemlere aktarın.",
    "cn.addNew": "Yeni Çek/Senet Ekle",
    "cn.cheque": "Çek",
    "cn.promissoryNote": "Senet",
    "cn.receivable": "Alacak",
    "cn.payable": "Borç",
    "cn.debtor": "Borçlu / Ödeyecek Kişi",
    "cn.bank": "Banka / Şube",
    "cn.serial": "Seri Numarası",
    "cn.dueDate": "Vade Tarihi",
    "cn.issueDate": "Düzenleme Tarihi",
    "cn.status": "Durum",
    "cn.pending": "Beklemede",
    "cn.paid": "Tahsil Edildi / Ödendi",
    "cn.cancelled": "İptal Edildi",
    "cn.returned": "İade Edildi",
    "cn.noItems": "Henüz kayıtlı çek veya senet bulunmuyor.",
    "cn.createTransaction": "İşlemlere Aktar",
    "cn.transferred": "İşlemlere başarıyla aktarıldı.",
    "cn.reminderTitle": "Çek & Senet Hatırlatıcı",
    "cn.reminderDesc": "Vadeli alacak ve borç belgelerinizi yönetin.",
    "cn.totalReceivables": "Toplam Alacak",
    "cn.pendingCollections": "Beklemedeki tahsilatlar",
    "cn.totalPayables": "Toplam Borç",
    "cn.pendingPayments": "Beklemedeki ödemeler",
    "cn.dueOverdue": "Vadesi Gelenler / Geçenler",
    "cn.itemsCount": "{count} Adet",
    "cn.totalPrefix": "Toplam: ",
    "cn.searchPlaceholder": "Borçlu adı, seri no veya açıklama ara...",
    "cn.allDocs": "Tüm Belgeler",
    "cn.allDirections": "Tüm Yönler",
    "cn.allStatuses": "Tüm Durumlar",
    "cn.collectedPaidStatus": "Tahsil Edildi/Ödendi",
    "cn.bouncedReturnedStatus": "Karşılıksız/İade",
    "cn.docDetail": "Belge Detayı",
    "cn.serialBank": "Seri No / Banka",
    "cn.dueIssue": "Vade / Keşide",
    "cn.bankNotSpecified": "Banka belirtilmemiş",
    "cn.overdueLabel": "Gecikti",
    "cn.todayLabel": "Bugün!",
    "cn.duePrefix": "Vade: ",
    "cn.issuePrefix": "Keşide: ",
    "cn.markPaidTooltip": "Tahsil Edildi / Ödendi İşaretle",
    "cn.debtorCreditor": "Borçlu/Alacaklı",
    "cn.addNewDocTitle": "Yeni Çek veya Senet Ekle",
    "cn.addNewDocDesc": "Vadeli alacak veya borç belgesi detaylarını girin.",
    "cn.docType": "Belge Türü",
    "cn.selectPlaceholder": "Seçin",
    "cn.docDirection": "Yön / İşlem",
    "cn.receivableReceived": "Alacak (Alınan)",
    "cn.payableIssued": "Borç (Verilen)",
    "cn.amountTL": "Tutar (TL)",
    "cn.serialPlaceholder": "Çek/Senet Seri No...",
    "cn.issueDateLabel": "Keşide / Düzenleme Tarihi",
    "cn.debtorPlaceholder": "Ad Soyad / Firma...",
    "cn.bankPlaceholder": "Garanti, Akbank vb...",
    "cn.relatedProject": "İlişkili Şirket / Proje",
    "cn.selectCompanyOptional": "Şirket Seçin (Opsiyonel)",
    "cn.noAssociation": "İlişkilendirme Yok",
    "cn.notesPlaceholder": "Ek notlar girin...",
    "cn.editDocTitle": "Belgeyi Düzenle",
    "cn.editDocDesc": "Mevcut çek veya senet kaydını düzenleyin.",
    "cn.docStatus": "Belge Durumu",
    "cn.selectStatus": "Durum Seçin",
    "cn.cancelledStatusFull": "İptal Edildi",
    "cn.returnedStatusFull": "Karşılıksız/İade",
    "cn.updateStatusTitle": "{type} Durumunu Güncelle",
    "cn.updateStatusDesc": "Bu belgeyi **Tahsil Edildi / Ödendi** olarak işaretlemek üzeresiniz.",
    "cn.docDetailsTitle": "Belge Detayları",
    "cn.autoRecordLedger": "Kasaya (İşlemlere) otomatik gelir/gider olarak kaydet",
    "cn.ledgerCategory": "İşlemin Ekleneceği Kategori",
    "cn.dismissBtn": "Vazgeç",
    "cn.confirmPaymentBtn": "Tahsil Et / Ödendi İşaretle",
    "cn.deleteTitle": "Kayıt Silinecek",
    "cn.deleteDesc": "Bu çek/senet kaydını silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
    "cn.deleteConfirmBtn": "Evet, Sil",

    // Settings
    "settings.title": "Uygulama Seçenekleri",
    "settings.theme": "Arayüz Teması",
    "settings.themeLight": "Açık Tema (Light Mode)",
    "settings.themeDark": "Koyu Tema (Dark Mode)",
    "settings.themeSystem": "Sistem Teması (System Default)",
    "settings.currency": "Varsayılan Para Birimi",
    "settings.autoLock": "Otomatik Kilit Süresi",
    "settings.autoLockDisabled": "Devre Dışı (Kilitlenmesin)",
    "settings.autoLockMin": "{min} Dakika Hareketsizlik",
    "settings.autoLockDesc": "Uygulamada herhangi bir hareket olmazsa ekran otomatik olarak kilitlenir. (Sadece şifre koruması aktifken çalışır)",
    "settings.language": "Dil / Language",
    
    // Backup and Cloud
    "settings.backupTitle": "Yerel Veri Yedekleme & Geri Yükleme",
    "settings.backupDesc": "Yerel verilerinizi JSON dosyası olarak bilgisayarınıza yedekleyebilir veya daha önce aldığınız bir yedek dosyasından verilerinizi geri yükleyebilirsiniz.",
    "settings.backupExport": "Yedek İndir (JSON)",
    "settings.backupImport": "Yedek Yükle (JSON)",
    "settings.cloudTitle": "Bulut Senkronizasyonu",
    "settings.cloudDesc": "Hesabınızla giriş yaparak verilerinizi güvenle bulutta saklayabilir ve diğer cihazlarınızla senkronize edebilirsiniz.",
    "settings.cloudDelete": "Bulut Verilerini Sil",
    "settings.cloudDeleteConfirm": "Tüm bulut verilerinizi silmek için 'ONAYLIYORUM' yazın:",
    
    // Encryption / Password Settings
    "settings.passTitle": "Ekran Kilidi & Şifreleme",
    "settings.passDesc": "Uygulamanın açılışında şifre koruması ekleyerek yerel verilerinizin şifrelenmesini sağlayın.",
    "settings.passEnable": "Şifre Korumasını Aktif Et",
    "settings.passDisable": "Şifre Korumasını Kaldır",

    "general.downloadCSV": "CSV İndir",
    "list.noItems": "Aradığınız kriterlere uygun işlem bulunamadı.",
    "form.paymentMethodOptional": "Ödeme Yöntemi (Opsiyonel)",
    "list.deleteTransaction": "İşlemi Sil",
    "list.deleteConfirm": "Bu işlemi silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",

    // Toasts and Dialogs
    "toast.saved": "Başarıyla kaydedildi.",
    "toast.updated": "Başarıyla güncellendi.",
    "toast.deleted": "Başarıyla silindi.",
    "toast.error": "Bir hata oluştu.",
    "toast.backupSuccess": "Yedek başarıyla yüklendi.",
    "toast.currencySet": "Varsayılan para birimi {val} olarak ayarlandı.",
    "toast.languageSet": "Uygulama dili Türkçe olarak ayarlandı.",
    "toast.syncSuccess": "Bulut senkronizasyonu tamamlandı.",

    // Category Manager
    "cat.title": "Kategoriler",
    "cat.new": "Yeni",
    "cat.incomeTitle": "Gelir Kategorileri",
    "cat.expenseTitle": "Gider Kategorileri",
    "cat.editTitle": "Kategoriyi Düzenle",
    "cat.addTitle": "Yeni Kategori Ekle",
    "cat.editDesc": "Kategori detaylarını güncelleyin.",
    "cat.addDesc": "Yeni bir gelir veya gider kategorisi oluşturun.",
    "cat.nameLabel": "Kategori Adı",
    "cat.namePlaceholder": "Örn: Market, Ulaşım...",
    "cat.typeLabel": "Tür",
    "cat.budgetLimit": "Aylık Bütçe Limiti ({symbol}) (Opsiyonel)",
    "cat.budgetPlaceholder": "Örn: 5000",
    "cat.budgetDesc": "Bu harcama kategorisi için aylık maksimum limit belirler.",
    "cat.colorLabel": "Renk",
    "cat.updateBtn": "Güncelle",
    "cat.addBtn": "Ekle",
    "cat.deleteTitle": "Kategoriyi Sil",
    "cat.deleteDesc": "Bu kategoriyi silmek istediğinizden emin misiniz? Bu kategoriye ait işlemler otomatik olarak **\"Diğer\"** kategorisine atanacaktır.",
    "cat.other": "Diğer",
    "cat.limitShort": "L",

    // Project Manager
    "proj.title": "Şirketler / Projeler",
    "proj.new": "Yeni",
    "proj.all": "Tüm Şirketler",
    "proj.empty": "Henüz şirket/proje eklenmemiş",
    "proj.passive": "Pasif",
    "proj.editTitle": "Şirket/Projeyi Düzenle",
    "proj.addTitle": "Yeni Şirket/Proje Ekle",
    "proj.editDesc": "Şirket veya proje detaylarını güncelleyin.",
    "proj.addDesc": "Yeni bir şirket veya proje oluşturun.",
    "proj.nameLabel": "Ad",
    "proj.namePlaceholder": "Örn: Ana Şirket, Proje A...",
    "proj.descLabel": "Açıklama (Opsiyonel)",
    "proj.descPlaceholder": "Şirket/proje hakkında kısa bilgi...",
    "proj.colorLabel": "Renk",
    "proj.activeLabel": "Aktif",
    "proj.deleteTitle": "Şirket/Projeyi Sil",
    "proj.deleteDesc": "Bu şirket/projeyi silmek istediğinizden emin misiniz? Bu projeye ait işlemler projeden çıkarılacaktır.",

    // Password Protection
    "pass.lockedTitle": "Uygulama Kilitli",
    "pass.enterPass": "Uygulamaya erişmek için şifrenizi girin",
    "pass.placeholder": "Şifreniz",
    "pass.errorInvalid": "Hatalı şifre veya veriler çözülemedi",
    "pass.errorGeneral": "Bir hata oluştu",
    "pass.unlocking": "Çözülüyor...",
    "pass.unlockBtn": "Kilidi Aç",
    "pass.forgotBtn": "Şifremi Unuttum",
    "pass.resetTitle": "Şifreyi Sıfırla",
    "pass.resetDesc": "Şifrenizi sıfırlamak için Google hesabınızla yeniden giriş yapmanız gerekmektedir. <br /><br /><strong class=\"text-amber-600 dark:text-amber-400\">Önemli Uyarı:</strong> Parolanız unutulduğu için şifrelenmiş yerel verileriniz çözülemeyecek ve bu cihazdan temizlenecektir. Google ile giriş yaptıktan sonra, buluttaki verileriniz (Supabase) otomatik olarak geri yüklenecektir.<br /><br />Bu işlem için mevcut oturumunuz kapatılacak ve Google giriş ekranına yönlendirileceksiniz. İnternet bağlantınızın olduğundan emin olun.",
    "pass.resetConfirmBtn": "Evet, Çıkış Yap ve Sıfırla",
    "pass.settingsTitle": "Şifre Koruması",
    "pass.statusActive": "Şifre koruması aktif (Veriler diskte şifreli saklanıyor)",
    "pass.removeBtn": "Şifre Korumasını Kaldır",
    "pass.newLabel": "Yeni Şifre",
    "pass.newPlaceholder": "En az 4 karakter",
    "pass.confirmLabel": "Şifreyi Onayla",
    "pass.confirmPlaceholder": "Şifreyi tekrar girin",
    "pass.settingUp": "Ayarlanıyor...",
    "pass.setupBtn": "Şifre Ayarla",
    "pass.errorShort": "Şifre en az 4 karakter olmalı",
    "pass.errorMismatch": "Şifreler eşleşmiyor",
    "pass.successSet": "Şifre başarıyla ayarlandı. Verileriniz yerel olarak şifrelendi.",
    "pass.errorSet": "Şifre ayarlanırken bir hata oluştu.",
    "pass.successRemove": "Şifre kaldırıldı. Verileriniz artık şifresiz saklanıyor.",
    "pass.errorRemove": "Şifre kaldırılırken bir hata oluştu.",
    "pass.hint": "Şifre koruması aktif olduğunda, uygulamaya her girişte şifre istenecek ve tüm yerel veriler şifrelenmiş olarak saklanacaktır.",

    // Cloud Sync
    "cloud.title": "Bulut Senkronizasyonu",
    "cloud.notConfigured": "Supabase yapılandırılmamış (.env dosyasını kontrol edin).",
    "cloud.loading": "Bulut işlemi yapılıyor...",
    "cloud.success": "Bulut işlemi başarılı.",
    "cloud.error": "Bulut işlemi başarısız.",
    "cloud.offline": "Çevrimdışı moddasınız.",
    "cloud.connected": "Buluta bağlısınız.",
    "cloud.envMissing": "Supabase ayarları yapılmamış. Lütfen .env dosyanıza VITE_SUPABASE_URL ve VITE_SUPABASE_ANON_KEY ekleyin.",
    "cloud.googleUser": "Google kullanıcısı",
    "cloud.signOut": "Çıkış",
    "cloud.deleteTitle": "Bulut Verilerini Sil",
    "cloud.deleteDesc": "Bu işlem buluttaki verilerinizi siler ve çıkış yapar.",
    "cloud.deleteBtn": "Bulut Verilerini Sil",
    "cloud.online": "Çevrimiçi",
    "cloud.offlineBadge": "Çevrimdışı",
    "cloud.syncPending": "Eşitleme Bekliyor",
    "cloud.uploadBtn": "Buluta Yükle",
    "cloud.downloadBtn": "Buluttan İndir",
    "cloud.hint": "Verileriniz Supabase üzerinde kullanıcı hesabınıza bağlı olarak saklanır. İsterseniz cihazınızda yerel olarak tutulmaya devam eder; buluta yükleme ve indirme işlemleri tamamen sizin kontrolünüzdeki yerlerdedir.",

    // Google Login
    "login.title": "Gelir Gider Takip",
    "login.subtitle": "Devam etmek için Google hesabınızla giriş yapın",
    "login.btn": "Google ile Giriş Yap",
    "login.hint": "Giriş yaptığınızda verileriniz güvenli şekilde bulutta senkronize edilir.",
    "login.envMissing": "Supabase yapılandırılmamış. .env dosyanıza VITE_SUPABASE_URL ve VITE_SUPABASE_ANON_KEY ekleyin.",
  },
  en: {
    // Navigation / Tabs
    "nav.home": "Dashboard",
    "nav.reports": "Reports",
    "nav.chequesNotes": "Cheques & Notes",
    "nav.settings": "Settings",
    "nav.title": "Expense Tracker",
    "nav.transactions": "Transactions",
    "nav.goals": "Goals",
    "nav.viewAllProjects": "View All Companies",
    "nav.allProjects": "All Companies",
    "nav.subTitle": "Your personal finance manager",
    "summary.totalBalance": "Total Balance",

    // General Words
    "general.income": "Income",
    "general.expense": "Expense",
    "general.amount": "Amount",
    "general.description": "Description",
    "general.category": "Category",
    "general.date": "Date",
    "general.paymentMethod": "Payment Method",
    "general.project": "Company / Project",
    "general.none": "Not Specified",
    "general.cash": "Cash",
    "general.creditCard": "Credit Card",
    "general.actions": "Actions",
    "general.save": "Save",
    "general.cancel": "Cancel",
    "general.delete": "Delete",
    "general.edit": "Edit",
    "general.active": "Active",
    "general.passive": "Passive",
    "general.loading": "Loading...",
    "general.search": "Search transactions...",
    "general.all": "All",
    "general.personal": "Personal (Non-Company)",
    "general.required": "This field is required",
    "general.success": "Success",
    "general.error": "Error",
    "general.type": "Type",
    "general.unknown": "Unknown",
    "general.currency": "Currency",
    "general.cashEmoji": "💵 Cash",
    "general.cardEmoji": "💳 Credit Card",
    "form.addIncome": "Add Income",
    "form.addExpense": "Add Expense",
    "form.selectDate": "Select Date",
    "form.descriptionOptional": "Description (Optional)",

    // Summary Cards
    "summary.totalIncome": "Total Income",
    "summary.totalExpense": "Total Expense",
    "summary.netBalance": "Net Balance",
    "summary.transactionCount": "Transactions",

    // Forms
    "form.addNewTransaction": "Add New Transaction",
    "form.editTransaction": "Edit Transaction",
    "form.editTransactionDesc": "Update the details of the selected transaction.",
    "form.mathHint": "0.00 or 100+50-20...",
    "form.selectCategory": "Select category",
    "form.selectPaymentMethod": "Select payment method",
    "form.selectProject": "Select company/project",
    "form.optional": "Optional",
    "form.notePlaceholder": "Transaction note...",
    "form.submitAdd": "Add",
    "form.quickTemplates": "Quick Templates",

    // Recurring Forms
    "form.addNewRecurring": "Add Recurring Transaction",
    "form.startDate": "Start Date",
    "form.endDate": "End Date",
    "form.hasEndDate": "Has end date",
    "form.isActive": "Active",
    "form.selectStartDate": "Select start date",
    "form.selectEndDate": "Select end date",
    "form.addRecurringIncome": "Add Recurring Income",
    "form.addRecurringExpense": "Add Recurring Expense",

    // Recurring Manager
    "rec.title": "Recurring Transactions",
    "rec.desc": "Manage your monthly recurring transactions like salary, rent, and subscriptions here. The system adds them automatically when their due dates arrive.",
    "rec.addNew": "New Recurring",
    "rec.activeState": "Status",
    "rec.noItems": "No recurring transactions defined yet.",
    "rec.addFirst": "Use the form above to create your first recurring transaction!",

    // Filter Bar
    "filter.viewMode": "View Mode",
    "filter.daily": "Daily",
    "filter.monthly": "Monthly",
    "filter.yearly": "Yearly",
    "filter.customRange": "Custom Date Range",
    "filter.minAmount": "Min Amount",
    "filter.maxAmount": "Max Amount",
    "filter.categories": "Categories",
    "filter.reset": "Clear Filters",
    "filter.advanced": "Advanced Filters",
    "month.jan": "January", "month.feb": "February", "month.mar": "March", "month.apr": "April", "month.may": "May", "month.jun": "June",
    "month.jul": "July", "month.aug": "August", "month.sep": "September", "month.oct": "October", "month.nov": "November", "month.dec": "December",
    "filter.view": "View:",
    "form.startDateShort": "Start",
    "form.endDateShort": "End",
    "filter.txDesc": "Transaction Description",
    "filter.searchPlaceholder": "Search in descriptions...",
    "filter.allMethods": "All Methods",
    "filter.cashOnly": "💵 Cash Only",
    "filter.cardOnly": "💳 Credit Card Only",
    "filter.amountRange": "Amount Range",
    "filter.clearSelection": "Clear Selection",
    "filter.resetAll": "Reset All Filters",

    // Charts
    "chart.monthlyTrend": "Income vs Expense Trend",
    "chart.cashFlow": "6-Month Cash Flow & Balance Forecast (Includes Recurring)",
    "chart.incomeDistribution": "Income Distribution",
    "chart.expenseDistribution": "Expense Distribution",
    "chart.companySummary": "Company Distribution Summary Report",
    "chart.noData": "No data available",

    // Cheques and Notes
    "cn.title": "Cheques & Promissory Notes",
    "cn.desc": "Record your receivable and payable cheques or notes, track their due dates, and transfer them to transactions with a single click.",
    "cn.addNew": "Add New Cheque/Note",
    "cn.cheque": "Cheque",
    "cn.promissoryNote": "Promissory Note",
    "cn.receivable": "Receivable",
    "cn.payable": "Payable",
    "cn.debtor": "Debtor / Payer",
    "cn.bank": "Bank / Branch",
    "cn.serial": "Serial Number",
    "cn.dueDate": "Due Date",
    "cn.issueDate": "Issue Date",
    "cn.status": "Status",
    "cn.pending": "Pending",
    "cn.paid": "Collected / Paid",
    "cn.cancelled": "Cancelled",
    "cn.returned": "Returned / Bounced",
    "cn.noItems": "No cheques or notes recorded yet.",
    "cn.createTransaction": "Transfer to Transactions",
    "cn.transferred": "Transferred to transactions successfully.",
    "cn.reminderTitle": "Cheques & Notes Reminder",
    "cn.reminderDesc": "Manage your post-dated receivable and payable documents.",
    "cn.totalReceivables": "Total Receivables",
    "cn.pendingCollections": "Pending collections",
    "cn.totalPayables": "Total Payables",
    "cn.pendingPayments": "Pending payments",
    "cn.dueOverdue": "Due / Overdue",
    "cn.itemsCount": "{count} Items",
    "cn.totalPrefix": "Total: ",
    "cn.searchPlaceholder": "Search debtor, serial no or description...",
    "cn.allDocs": "All Documents",
    "cn.allDirections": "All Directions",
    "cn.allStatuses": "All Statuses",
    "cn.collectedPaidStatus": "Collected/Paid",
    "cn.bouncedReturnedStatus": "Bounced/Returned",
    "cn.docDetail": "Document Detail",
    "cn.serialBank": "Serial No / Bank",
    "cn.dueIssue": "Due / Issue",
    "cn.bankNotSpecified": "Bank not specified",
    "cn.overdueLabel": "Overdue",
    "cn.todayLabel": "Today!",
    "cn.duePrefix": "Due: ",
    "cn.issuePrefix": "Issue: ",
    "cn.markPaidTooltip": "Mark as Collected / Paid",
    "cn.debtorCreditor": "Debtor/Creditor",
    "cn.addNewDocTitle": "Add New Cheque or Note",
    "cn.addNewDocDesc": "Enter details of the post-dated document.",
    "cn.docType": "Document Type",
    "cn.selectPlaceholder": "Select",
    "cn.docDirection": "Direction",
    "cn.receivableReceived": "Receivable (Received)",
    "cn.payableIssued": "Payable (Issued)",
    "cn.amountTL": "Amount (TL)",
    "cn.serialPlaceholder": "Cheque/Note Serial No...",
    "cn.issueDateLabel": "Issue / Settlement Date",
    "cn.debtorPlaceholder": "Name / Company...",
    "cn.bankPlaceholder": "Garanti, Akbank etc...",
    "cn.relatedProject": "Related Company / Project",
    "cn.selectCompanyOptional": "Select Company (Optional)",
    "cn.noAssociation": "No Association",
    "cn.notesPlaceholder": "Enter additional notes...",
    "cn.editDocTitle": "Edit Document",
    "cn.editDocDesc": "Edit the details of the selected document.",
    "cn.docStatus": "Document Status",
    "cn.selectStatus": "Select Status",
    "cn.cancelledStatusFull": "Cancelled",
    "cn.returnedStatusFull": "Bounced/Returned",
    "cn.updateStatusTitle": "Update {type} Status",
    "cn.updateStatusDesc": "You are about to mark this document as Collected / Paid.",
    "cn.docDetailsTitle": "Document Details",
    "cn.autoRecordLedger": "Automatically record to ledger as income/expense",
    "cn.ledgerCategory": "Category for Transaction",
    "cn.dismissBtn": "Cancel",
    "cn.confirmPaymentBtn": "Collect / Mark Paid",
    "cn.deleteTitle": "Delete Record",
    "cn.deleteDesc": "Are you sure you want to delete this cheque/note record? This action cannot be undone.",
    "cn.deleteConfirmBtn": "Yes, Delete",

    // Settings
    "settings.title": "Application Settings",
    "settings.theme": "Theme Mode",
    "settings.themeLight": "Light Theme",
    "settings.themeDark": "Dark Theme",
    "settings.themeSystem": "System Default",
    "settings.currency": "Default Currency",
    "settings.autoLock": "Auto Lock Timeout",
    "settings.autoLockDisabled": "Disabled (Do not lock)",
    "settings.autoLockMin": "{min} Minutes Inactivity",
    "settings.autoLockDesc": "The screen locks automatically after a period of inactivity. (Works only when password protection is active)",
    "settings.language": "Language / Dil",

    // Backup and Cloud
    "settings.backupTitle": "Local Backup & Restore",
    "settings.backupDesc": "You can backup your local data as a JSON file to your computer or restore your data from a previously created backup file.",
    "settings.backupExport": "Export Backup (JSON)",
    "settings.backupImport": "Import Backup (JSON)",
    "settings.cloudTitle": "Cloud Synchronization",
    "settings.cloudDesc": "Log in to safely store your data in the cloud and synchronize it with your other devices.",
    "settings.cloudDelete": "Delete Cloud Data",
    "settings.cloudDeleteConfirm": "Type 'ONAYLIYORUM' to delete all your cloud data:",

    // Encryption / Password Settings
    "settings.passTitle": "Screen Lock & Encryption",
    "settings.passDesc": "Protect your local data by adding a password lock on application startup.",
    "settings.passEnable": "Enable Password Protection",
    "settings.passDisable": "Disable Password Protection",

    "general.downloadCSV": "Download CSV",
    "list.noItems": "No transactions found matching your criteria.",
    "form.paymentMethodOptional": "Payment Method (Optional)",
    "list.deleteTransaction": "Delete Transaction",
    "list.deleteConfirm": "Are you sure you want to delete this transaction? This action cannot be undone.",

    // Toasts and Dialogs
    "toast.saved": "Saved successfully.",
    "toast.updated": "Updated successfully.",
    "toast.deleted": "Deleted successfully.",
    "toast.error": "An error occurred.",
    "toast.backupSuccess": "Backup loaded successfully.",
    "toast.currencySet": "Default currency set to {val}.",
    "toast.languageSet": "Language set to English.",
    "toast.syncSuccess": "Cloud sync completed successfully.",

    // Category Manager
    "cat.title": "Categories",
    "cat.new": "New",
    "cat.incomeTitle": "Income Categories",
    "cat.expenseTitle": "Expense Categories",
    "cat.editTitle": "Edit Category",
    "cat.addTitle": "Add New Category",
    "cat.editDesc": "Update the details of the category.",
    "cat.addDesc": "Create a new income or expense category.",
    "cat.nameLabel": "Category Name",
    "cat.namePlaceholder": "e.g. Groceries, Transport...",
    "cat.typeLabel": "Type",
    "cat.budgetLimit": "Monthly Budget Limit ({symbol}) (Optional)",
    "cat.budgetPlaceholder": "e.g. 5000",
    "cat.budgetDesc": "Sets a maximum monthly spending limit for this category.",
    "cat.colorLabel": "Color",
    "cat.updateBtn": "Update",
    "cat.addBtn": "Add",
    "cat.deleteTitle": "Delete Category",
    "cat.deleteDesc": "Are you sure you want to delete this category? Transactions belonging to this category will automatically be reassigned to the **\"Other\"** category.",
    "cat.other": "Other",
    "cat.limitShort": "L",

    // Project Manager
    "proj.title": "Companies / Projects",
    "proj.new": "New",
    "proj.all": "All Companies",
    "proj.empty": "No companies/projects added yet",
    "proj.passive": "Passive",
    "proj.editTitle": "Edit Company/Project",
    "proj.addTitle": "Add New Company/Project",
    "proj.editDesc": "Update company or project details.",
    "proj.addDesc": "Create a new company or project.",
    "proj.nameLabel": "Name",
    "proj.namePlaceholder": "e.g. Main Company, Project A...",
    "proj.descLabel": "Description (Optional)",
    "proj.descPlaceholder": "Brief information about company/project...",
    "proj.colorLabel": "Color",
    "proj.activeLabel": "Active",
    "proj.deleteTitle": "Delete Company/Project",
    "proj.deleteDesc": "Are you sure you want to delete this company/project? Transactions associated with it will lose their association.",

    // Password Protection
    "pass.lockedTitle": "Application Locked",
    "pass.enterPass": "Enter your password to access the application",
    "pass.placeholder": "Your password",
    "pass.errorInvalid": "Incorrect password or data could not be decrypted",
    "pass.errorGeneral": "An error occurred",
    "pass.unlocking": "Decrypting...",
    "pass.unlockBtn": "Unlock",
    "pass.forgotBtn": "Forgot Password",
    "pass.resetTitle": "Reset Password",
    "pass.resetDesc": "To reset your password, you need to sign in again with your Google account. <br /><br /><strong class=\"text-amber-600 dark:text-amber-400\">Important Warning:</strong> Since your password is forgotten, your encrypted local data cannot be decrypted and will be cleared from this device. After signing in with Google, your cloud data (Supabase) will be automatically restored.<br /><br />Your current session will be closed and you will be redirected to the Google login page. Make sure you have an internet connection.",
    "pass.resetConfirmBtn": "Yes, Log Out and Reset",
    "pass.settingsTitle": "Password Protection",
    "pass.statusActive": "Password protection active (Data is stored encrypted on disk)",
    "pass.removeBtn": "Disable Password Protection",
    "pass.newLabel": "New Password",
    "pass.newPlaceholder": "At least 4 characters",
    "pass.confirmLabel": "Confirm Password",
    "pass.confirmPlaceholder": "Enter password again",
    "pass.settingUp": "Setting up...",
    "pass.setupBtn": "Set Password",
    "pass.errorShort": "Password must be at least 4 characters",
    "pass.errorMismatch": "Passwords do not match",
    "pass.successSet": "Password set successfully. Your data has been encrypted locally.",
    "pass.errorSet": "An error occurred while setting the password.",
    "pass.successRemove": "Password protection disabled. Your data is now stored unencrypted.",
    "pass.errorRemove": "An error occurred while disabling password protection.",
    "pass.hint": "When password protection is enabled, you will be prompted for a password on each startup, and all local data will be stored encrypted.",

    // Cloud Sync
    "cloud.title": "Cloud Synchronization",
    "cloud.notConfigured": "Supabase not configured (check .env file).",
    "cloud.loading": "Cloud operation in progress...",
    "cloud.success": "Cloud operation successful.",
    "cloud.error": "Cloud operation failed.",
    "cloud.offline": "You are offline.",
    "cloud.connected": "Connected to cloud.",
    "cloud.envMissing": "Supabase settings are missing. Please add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to your .env file.",
    "cloud.googleUser": "Google User",
    "cloud.signOut": "Sign Out",
    "cloud.deleteTitle": "Delete Cloud Data",
    "cloud.deleteDesc": "This action deletes your data from the cloud and logs you out.",
    "cloud.deleteBtn": "Delete Cloud Data",
    "cloud.online": "Online",
    "cloud.offlineBadge": "Offline",
    "cloud.syncPending": "Sync Pending",
    "cloud.uploadBtn": "Upload to Cloud",
    "cloud.downloadBtn": "Download from Cloud",
    "cloud.hint": "Your data is stored on Supabase linked to your user account. It can continue to be kept locally on your device if you prefer; uploading and downloading are entirely under your control.",

    // Google Login
    "login.title": "Expense Tracker",
    "login.subtitle": "Sign in with your Google account to continue",
    "login.btn": "Sign in with Google",
    "login.hint": "When you sign in, your data is securely synchronized in the cloud.",
    "login.envMissing": "Supabase not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to your .env file.",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('gelir-gider-language') as Language) || 'tr';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('gelir-gider-language', lang);
  };

  const t = (key: string, replacements?: Record<string, string | number>): string => {
    const dict = translations[language];
    let value = (dict as any)[key] || key;

    if (replacements) {
      Object.entries(replacements).forEach(([k, v]) => {
        value = value.replace(`{${k}}`, String(v));
      });
    }

    return value;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
